### ISSUE TITLE
YunserialTerminal is blocked by 'bridge: filtering via arp/ip/ip6tables is no longer available by default'

### ISSUE THREAD

**Issue by scenaristeur** [nxhack/openwrt-yun-build-extra#4] opened 2018-08-28 21:54 UTC
I've flashed my yun (rev2) with : 
u-boot-linino-yun.bin, 
linino-caldata.bin
& openwrt...arduino-yun-squash....bin
+
'setenv mtdparts "spi0.0:256k(u-boot)ro,64k(u-boot-env),15936k(firmware),64k(nvram),64k(art)ro"
setenv bootcmd "run addboard; run addtty; run addparts; run addrootfs; bootm 0x9f050000 || bootm 0x9fea0000"
saveenv'

but now, with the YunSerialTerminal sketch, the console seems to block at : 
[...]
[    2.139206] eth1: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    2.143400] NET: Registered protocol family 10
[    2.149540] NET: Registered protocol family 17
[    2.151005] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    2.157117] 8021q: 802.1Q VLAN Support v1.8

.. and nothing more ??
 
The yun boots, but I'm not able to access linux Terminal from the Arduino Console as I could before...

**Comment by nxhack** [comment] 2018-08-29 06:25
Since there is no development environment at hand, it can not be confirmed immediately. If you have any progress please let me know.

**Comment by nxhack** [comment] 2018-11-21 01:50
I will close it. Please do not hesitate to reopen.

**Closed as completed by nxhack** 2018-11-21 01:50 UTC
